DROP DATABASE IF EXISTS baby;
CREATE DATABASE baby;
USE baby;

CREATE TABLE `users` (
`username` VARCHAR(255) NOT NULL,
`password` VARCHAR(255) NOT NULL
);

CREATE TABLE `slideshows` (
`id` INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
`type` VARCHAR(255) NOT NULL,
`name` VARCHAR(255) NOT NULL
);

CREATE TABLE `images` (
`id` INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
`type` VARCHAR(255) NOT NULL,
`name` VARCHAR(255) NOT NULL,
`text` VARCHAR(255) NULL,
`png` VARCHAR(255) NOT NULL,
`default_mp3` VARCHAR(255) NULL,
`custom_mp3` VARCHAR(255) NULL
);